fix(form-mapping): add missing classes and remove lombok
bonitasoft/bonita-artifacts-model pull request #17
Opened 2023-07-24 14:05 UTC by akantcheff

- remove lombok annotations because it is not compatible with jaxb2-maven-plugin
- add missing classes `FormMapping` & `FormMappingSearchDescriptor`
- add missing source path for schemagen task

2023-07-24 14:09 UTC, akantcheff commented
Note: the issue https://github.com/mojohaus/jaxb2-maven-plugin/issues/181 is still opened on `jaxb2-maven-plugin` to support lombok

2023-07-24 15:22 UTC, rbioteau requested changes

2023-07-25 07:18 UTC, akantcheff commented on form-mapping-model/src/main/java/org/bonitasoft/engine/form/FormMapping.java
> +public class FormMapping implements BaseElement {
But this object is part of the `form-mapping.xsd`

2023-07-25 07:22 UTC, rbioteau commented on form-mapping-model/src/main/java/org/bonitasoft/engine/form/FormMapping.java
> +public class FormMapping implements BaseElement {
By mistake... It is never use in the FormMappingModelBuilder

2023-07-27 07:56 UTC, merged